-- V1 supports Robinhood and Base. This migration expands the checks created
-- by 0002 without rewriting an already-applied migration.
DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT n.nspname AS schema_name, c.relname AS table_name, con.conname AS constraint_name
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE con.contype = 'c'
      AND pg_get_constraintdef(con.oid) LIKE '%chain_id IN (4663, 46630)%'
  LOOP
    EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', target.schema_name, target.table_name, target.constraint_name);
  END LOOP;
END $$;

-- PostgreSQL may normalize an inline IN check to `= ANY (ARRAY[...])`, so
-- also remove the names generated by 0002 explicitly.
ALTER TABLE wallet DROP CONSTRAINT IF EXISTS wallet_chain_id_check;
ALTER TABLE edition_request DROP CONSTRAINT IF EXISTS edition_request_chain_id_check;
ALTER TABLE edition DROP CONSTRAINT IF EXISTS edition_chain_id_check;
ALTER TABLE signed_seaport_order DROP CONSTRAINT IF EXISTS signed_seaport_order_chain_id_check;

ALTER TABLE wallet DROP CONSTRAINT IF EXISTS wallet_chain_id_supported;
ALTER TABLE edition_request DROP CONSTRAINT IF EXISTS edition_request_chain_id_supported;
ALTER TABLE edition DROP CONSTRAINT IF EXISTS edition_chain_id_supported;
ALTER TABLE signed_seaport_order DROP CONSTRAINT IF EXISTS signed_seaport_order_chain_id_supported;

ALTER TABLE wallet ADD CONSTRAINT wallet_chain_id_supported CHECK (chain_id IN (4663,46630,8453,84532));
ALTER TABLE edition_request ADD CONSTRAINT edition_request_chain_id_supported CHECK (chain_id IN (4663,46630,8453,84532));
ALTER TABLE edition ADD CONSTRAINT edition_chain_id_supported CHECK (chain_id IN (4663,46630,8453,84532));
ALTER TABLE signed_seaport_order ADD CONSTRAINT signed_seaport_order_chain_id_supported CHECK (chain_id IN (4663,46630,8453,84532));
